# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: comanda

before:
  hooks:
    - go mod tidy

builds:
  - id: comanda
    main: .
    binary: comanda
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/kris-hansen/comanda/cmd.version=v{{.Version}}

archives:
  # tar.gz archives (used by homebrew)
  - id: targz
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
  # zip archives (alternative format, especially for Windows)
  - id: zip
    format: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kris-hansen
    name: comanda
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: comanda
    ids:
      - targz  # Use only tar.gz archives for homebrew
    repository:
      owner: kris-hansen
      name: homebrew-comanda
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: .
    homepage: "https://github.com/kris-hansen/comanda"
    description: "Chain of Models and Actions - declarative LLM workflow orchestration"
    license: "MIT"
    install: |
      bin.install "comanda"
    test: |
      system "#{bin}/comanda", "version"
      system "#{bin}/comanda", "help", "configure"
